### model
model_name_or_path: saves/olmo/model_lora_0_pt/model/
adapter_name_or_path: saves/olmo/lora_1_pt/

### method
stage: pt
do_train: true
finetuning_type: model_lora
lora_target: q_proj,v_proj
lora_rank: 8

### dataset
dataset: c4_demo
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/olmo/model_lora_1_pt/
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
