### model
model_name_or_path: saves/S1_all/110/latest/model/
adapter_name_or_path: saves/S1_all/001/latest
resume_from_checkpoint: saves/S1_all/101/latest

### method
stage: pt
do_train: true
finetuning_type: model_lora
lora_target: q_proj,v_proj
lora_rank: 64

ddp_timeout: 180000000
### dataset
tokenized_path: pretrain_token/S1_all/101/
# dataset_dir: data/S1_all/101
# dataset: c4_demo
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 128
# packing: true

### output
output_dir: saves/S1_all/101/
logging_steps: 100
save_steps: 1000
save_total_limit: 5
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 2000
fp16: true

### eval
val_size: 0.001
per_device_eval_batch_size: 4
evaluation_strategy: steps
eval_steps: 50000

report_to: none
