### model
model_name_or_path: saves/S1_all/101/model/
adapter_name_or_path: saves/S1_all/110/lora_default/,saves/olmo/101/lora_default/

### method
stage: pt
do_train: true
finetuning_type: model_lora
lora_target: q_proj,v_proj
lora_rank: 64

ddp_timeout: 180000000
### dataset
tokenized_path: pretrain_token/S1_all/111/
dataset_dir: data/S1_all/111
# dataset: c4_demo
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 128
# packing: true

### output
output_dir: saves/S1_all/111/
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 2000
fp16: true

### eval
val_size: 0.01
per_device_eval_batch_size: 4
evaluation_strategy: steps
eval_steps: 50000

report_to: none
